// Integration test with audio generated by this project; no YouTube download required.
const { execFile } = require('node:child_process');
const { promisify } = require('node:util');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const http = require('node:http');
const assert = require('node:assert/strict');
const { makeArgs } = require('../src/core');
const exec = promisify(execFile);
async function main() {
  const target = process.platform === 'win32' ? 'win' : `mac-${process.arch}`;
  const ext = process.platform === 'win32' ? '.exe' : '';
  const bin = path.resolve(__dirname, '..', 'resources', 'bin', target);
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'youtube-mp3-tools-'));
  const server = http.createServer();
  try {
    const fixture = path.join(dir, 'fixture.wav');
    await exec(path.join(bin, 'ffmpeg' + ext), ['-f', 'lavfi', '-i', 'sine=frequency=440:duration=1', fixture], { windowsHide: true, timeout: 30000 });
    const audio = await fs.readFile(fixture);
    server.on('request', (_req, res) => { res.writeHead(200, { 'Content-Type': 'audio/wav', 'Content-Length': audio.length }); res.end(audio); });
    await new Promise((resolve, reject) => { server.once('error', reject); server.listen(0, '127.0.0.1', resolve); });
    const url = `http://127.0.0.1:${server.address().port}/fixture.wav`;
    const { stdout } = await exec(path.join(bin, 'yt-dlp' + ext), makeArgs(url, dir, bin), { windowsHide: true, timeout: 60000, maxBuffer: 1024 * 1024 });
    const output = stdout.split(/\r?\n/).find(line => line.startsWith('FILE:'))?.slice(5);
    assert.ok(output?.endsWith('.mp3'), stdout);
    const { stdout: metadata } = await exec(path.join(bin, 'ffprobe' + ext), ['-v', 'quiet', '-show_streams', '-of', 'json', output], { timeout: 10000 });
    assert.equal(JSON.parse(metadata).streams[0].codec_name, 'mp3');
    const { stdout: denoVersion } = await exec(path.join(bin, 'deno' + ext), ['--version'], { timeout: 10000 });
    assert.match(denoVersion, /deno 2/);
    console.log('TOOLS OK: audio propio → yt-dlp → FFmpeg → MP3 validado con FFprobe; Deno ejecutable.');
  } finally { server.close(); await fs.rm(dir, { recursive: true, force: true }); }
}
main().catch(error => { console.error(error); process.exitCode = 1; });
